/**
 * verify_signatures core logic tests.
 */

import { beforeAll, describe, expect, it } from 'vitest';
import { Verdict } from '../../src/constants.js';
import { parsePdfBytes } from '../../src/services/pdf-parser.js';
import { verifySignatures } from '../../src/services/verification-service.js';
import {
  createSignedPdf,
  createTestIdentity,
  type TestIdentity,
  tamperSignedPdf,
} from '../helpers/signed-pdf.js';

let identity: TestIdentity;
let signedPdf: Uint8Array;

beforeAll(async () => {
  identity = await createTestIdentity();
  signedPdf = await createSignedPdf(identity);
});

describe('verifySignatures', () => {
  it('verdict is valid for an untouched signed PDF', async () => {
    const parsed = await parsePdfBytes(signedPdf);
    const reports = await verifySignatures(parsed);

    expect(reports).toHaveLength(1);
    const report = reports[0];
    expect(report.verdict).toBe(Verdict.VALID);
    expect(report.trust).toBe('not_evaluated');
    expect(report.coversEntireFile).toBe(true);
    expect(report.cms?.digestMatches).toBe(true);
    expect(report.cms?.signatureVerified).toBe(true);
    expect(report.cms?.digestAlgorithm).toBe('SHA-256');
    expect(report.fieldName).toBe('Signature1');
  });

  it('reports signer certificate details', async () => {
    const parsed = await parsePdfBytes(signedPdf);
    const [report] = await verifySignatures(parsed);

    const cert = report.cms?.signerCertificate;
    expect(cert).toBeTruthy();
    expect(cert?.subject).toContain('CN=pdf-verify-mcp test');
    expect(cert?.isSelfSigned).toBe(true);
    expect(cert?.isExpiredNow).toBe(false);
  });

  it('verdict is invalid when signed bytes are tampered', async () => {
    const tampered = tamperSignedPdf(signedPdf);
    const parsed = await parsePdfBytes(tampered);
    const [report] = await verifySignatures(parsed);

    expect(report.verdict).toBe(Verdict.INVALID);
    expect(report.cms?.digestMatches).toBe(false);
  });

  it('unsupported SubFilter yields indeterminate with a note', async () => {
    // adbe.pkcs7.sha1 is not generated by helpers; simulate by string replacing
    const text = Buffer.from(signedPdf).toString('latin1');
    const replaced = text.replace('/ETSI.CAdES.detached ', '/adbe.pkcs7.sha1     ');
    const parsed = await parsePdfBytes(new Uint8Array(Buffer.from(replaced, 'latin1')));
    const [report] = await verifySignatures(parsed);

    expect(report.verdict).toBe(Verdict.INDETERMINATE);
    expect(report.notes.join(' ')).toContain('not supported');
  });

  it('returns empty report list for a PDF without signatures', async () => {
    const { PDFDocument } = await import('pdf-lib');
    const doc = await PDFDocument.create();
    doc.addPage();
    const bytes = await doc.save({ useObjectStreams: false });
    const parsed = await parsePdfBytes(bytes);
    const reports = await verifySignatures(parsed);
    expect(reports).toHaveLength(0);
  });
});
