/**
 * verify_signatures core logic tests.
 */

import { beforeAll, describe, expect, it } from 'vitest';
import { TrustStatus, Verdict } from '../../src/constants.js';
import { parsePdfBytes } from '../../src/services/pdf-parser.js';
import { verifySignatures } from '../../src/services/verification-service.js';
import {
  createSignedPdf,
  createTestIdentity,
  type TestIdentity,
  tamperSignedPdf,
} from '../helpers/signed-pdf.js';

let identity: TestIdentity;
let signedPdf: Uint8Array;

beforeAll(async () => {
  identity = await createTestIdentity();
  signedPdf = await createSignedPdf(identity);
});

describe('verifySignatures', () => {
  it('verdict is valid for an untouched signed PDF', async () => {
    const parsed = await parsePdfBytes(signedPdf);
    const reports = await verifySignatures(parsed);

    expect(reports).toHaveLength(1);
    const report = reports[0];
    expect(report.verdict).toBe(Verdict.VALID);
    expect(report.trust.status).toBe(TrustStatus.NOT_EVALUATED);
    expect(report.coversEntireFile).toBe(true);
    expect(report.cms?.digestMatches).toBe(true);
    expect(report.cms?.signatureVerified).toBe(true);
    expect(report.cms?.digestAlgorithm).toBe('SHA-256');
    expect(report.fieldName).toBe('Signature1');
  });

  it('reports signer certificate details', async () => {
    const parsed = await parsePdfBytes(signedPdf);
    const [report] = await verifySignatures(parsed);

    const cert = report.cms?.signerCertificate;
    expect(cert).toBeTruthy();
    expect(cert?.subject).toContain('CN=pdf-verify-mcp test');
    expect(cert?.isSelfSigned).toBe(true);
    expect(cert?.isExpiredNow).toBe(false);
  });

  it('verdict is invalid when signed bytes are tampered', async () => {
    const tampered = tamperSignedPdf(signedPdf);
    const parsed = await parsePdfBytes(tampered);
    const [report] = await verifySignatures(parsed);

    expect(report.verdict).toBe(Verdict.INVALID);
    expect(report.cms?.digestMatches).toBe(false);
  });

  it('unsupported SubFilter yields indeterminate with a note', async () => {
    // adbe.pkcs7.sha1 is not generated by helpers; simulate by string replacing
    const text = Buffer.from(signedPdf).toString('latin1');
    const replaced = text.replace('/ETSI.CAdES.detached ', '/adbe.pkcs7.sha1     ');
    const parsed = await parsePdfBytes(new Uint8Array(Buffer.from(replaced, 'latin1')));
    const [report] = await verifySignatures(parsed);

    expect(report.verdict).toBe(Verdict.INDETERMINATE);
    expect(report.notes.join(' ')).toContain('not supported');
  });

  it('returns empty report list for a PDF without signatures', async () => {
    const { PDFDocument } = await import('pdf-lib');
    const doc = await PDFDocument.create();
    doc.addPage();
    const bytes = await doc.save({ useObjectStreams: false });
    const parsed = await parsePdfBytes(bytes);
    const reports = await verifySignatures(parsed);
    expect(reports).toHaveLength(0);
  });
});

describe('document timestamps (ETSI.RFC3161)', () => {
  let tsa: TestIdentity;

  beforeAll(async () => {
    tsa = await createTestIdentity();
  });

  // Regression: pkijs re-checks the TSTInfo messageImprint against `data` even for
  // encapsulated content, and threw "Missed detached data input array" when the
  // ByteRange bytes were not passed. All three real-world specimen families
  // (pyHanko, esig/dss, kanpō/AMANO) hit this before the fix.
  it('a valid document timestamp verifies', async () => {
    const pdf = await createSignedPdf(tsa, { subFilter: 'ETSI.RFC3161' });
    const parsed = await parsePdfBytes(pdf);
    const [report] = await verifySignatures(parsed);

    expect(report.verdict).toBe(Verdict.VALID);
    expect(report.cms?.digestMatches).toBe(true);
    expect(report.cms?.signatureVerified).toBe(true);
    expect(report.cms?.error).toBeNull();
  });

  it('verdict is invalid when the timestamped bytes are tampered', async () => {
    const pdf = await createSignedPdf(tsa, { subFilter: 'ETSI.RFC3161' });
    const parsed = await parsePdfBytes(tamperSignedPdf(pdf));
    const [report] = await verifySignatures(parsed);

    expect(report.verdict).toBe(Verdict.INVALID);
    expect(report.cms?.digestMatches).toBe(false);
  });

  it('verdict is invalid (not indeterminate) when the TSA signature computes false', async () => {
    // Flip the last DER byte = tail of the TSA signature value. The imprint
    // still matches, so this must be a disproof, not "could not measure".
    const pdf = await createSignedPdf(tsa, {
      subFilter: 'ETSI.RFC3161',
      mutateCms: (cms) => {
        const copy = cms.slice();
        copy[copy.length - 1] ^= 0xff;
        return copy;
      },
    });
    const parsed = await parsePdfBytes(pdf);
    const [report] = await verifySignatures(parsed);

    expect(report.verdict).toBe(Verdict.INVALID);
    expect(report.cms?.digestMatches).toBe(true);
    expect(report.cms?.signatureVerified).toBe(false);
  });
});
